apiVersion: v1
kind: Namespace
metadata:
  name: nginx
spec: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      location /metrics {
          stub_status;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      name: nginx
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
    - port: 9113
      name: nginx-exporter
      targetPort: 9113
      nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        metrics.dynatrace.com/port: '9113'
        metrics.dynatrace.com/scrape: 'true'
        metrics.dynatrace.com/secure: 'false'
        metrics.dynatrace.com/path: '/metrics'
        metrics.dynatrace.com/filter: | 
          {
          "mode":"exclude",
          "names":["*build*"]
          }

    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter'
          args:
            - '-nginx.scrape-uri=http://localhost:80/metrics'
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 9113
      volumes:
      - name: nginx-config
        configMap: 
          name: nginx-conf