apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations: #annotations to enable scraping of the metrics endpoint
        metrics.dynatrace.com/port: '9113' #container port from the Prometheus exporter sidecar
        metrics.dynatrace.com/scrape: 'true'
        metrics.dynatrace.com/secure: 'false'
        metrics.dynatrace.com/path: '/metrics'
        metrics.dynatrace.com/filter: | 
          {
          "mode":"exclude",
          "names":["*build*"]
          }

    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80 #port for the website
          volumeMounts: #mounting configuration for NGINX Server
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
        - name: nginx-exporter # adding Prometheus exporter as sidecar
          image: 'nginx/nginx-prometheus-exporter'
          args:
            - '-nginx.scrape-uri=http://localhost:80/metrics'
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 9113 #Port for metric endpoint
      volumes: #adding ConfigMap as Volume
      - name: nginx-config
        configMap: 
          name: nginx-conf